<!--- Beginn des Codefragments --->



<table border="0" ><tr><td>

<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" 

codebase="http://active.macromedia.com/flash2/cabs/swflash.cab#version=4,0,0,0" 

ID=deutschland WIDTH=151 HEIGHT=178>

<PARAM NAME=movie VALUE="http://wetter.rtl.de/extern/generell/generator/deutschland/wetter_home.swf?id=29125&key=d5cf311360c0110fa6d89971881f07e2"> 

<PARAM NAME=menu VALUE=false>

<PARAM NAME=quality VALUE=high>

<PARAM NAME=bgcolor VALUE=#295D9C> 

<EMBED src="http://wetter.rtl.de/extern/generell/generator/deutschland/wetter_home.swf?id=29125&key=d5cf311360c0110fa6d89971881f07e2" 

quality=high menu=false bgcolor=#295D9C width="151" height="178" TYPE="application/x-shockwave-flash" 

PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">

</EMBED></OBJECT></td></tr></table>





<!--- Ende des Codefragments --->

