<?php
/*
        Copyright (C) 2000-2003 Liquid Bytes (R) Technologies, Germany. All rights reserved.
        http://www.liquidbytes.net/

        This file is part of the Liquid Bytes (R) Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 20.09.2003
*/

?>
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr>
<td width="180" bgcolor="#cccccc" valign="top" background="">
<p style="text-align: center">
<a href="http://freshmeat.net/projects/awf/"><img src="img/built_with_awf.png" border="0" /></a></p>
</td>
<td width="10" align="left">
&nbsp;
</td>
<td align="left">
<table border="0" cellpadding="0" cellspacing="0"><tr><td>
<a href="javascript:open_print_window()"><?=get_image_tag('img/small_edit/print.gif')?></a>
</td><td>&nbsp;<a href="javascript:open_print_window()">Print</a></td></tr></table>
</td>
<td align="right">
<span style="font-size:11px">
This website is powered by Liquid Bytes&reg; <a href="http://www.liquidbytes.net/awf/">Adaptive Website 
Framework</a>
<br/> 
Copyright &copy; 2000-2003 <a href="http://www.liquidbytes.net/">Liquid Bytes&reg; Technologies, Germany</a>. All rights reserved.
</span>
</td>
<td width="10">
&nbsp;
</td>
</tr>
</table>
