<br /><br />

<table width="100%">
<tr><td width="175"></td><td>
<a href="javascript:open_print_window()"><?=get_image_tag('img/small_edit/print.gif')?></a>
&nbsp;<a href="javascript:open_print_window()">Drucken</a>
</td></tr>
</table>
<div align="center"><small>Hinweise und Bemerkungen an
<script language="javascript" type="text/javascript">
  <!--
  var aka = "Christoph Griep"
  var prefix = "griep"
  var domain = "oszimt.de"
  document.write("<a h"+"ref=" + "mail" + "to:" + prefix + "@" + domain + ">" + aka + "</a>" + ".")
  //-->
</script>
</small></div>