<?php
/*
        Copyright (C) 2000-2002 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/

        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 23.06.2002
*/
?>

<div class="rechtsbuendig">
<a href="javascript:open_print_window()"><?=get_image_tag('img/small_edit/print.gif')?></a>
&nbsp;<a href="javascript:open_print_window()">Drucken</a>
&nbsp;&nbsp;&nbsp;
<a href="javascript:open_PDF_window()"><?=get_image_tag('img/icons_16/pdf.png')?></a>&nbsp;
<a href="javascript:open_PDF_window()">PDF</a></div>
<div class="lbfooter">
&copy; 2003-2012
<script language="javascript" type="text/javascript">
<!--
  var aka = "Suchtprophylaxe"
  var prefix = "sucht000"
  var domain = "suchtprophylaxe-berlin.schule.de"
  document.write('<a style="color:white" hr'+'ef="mailto:' + prefix + "@" + domain + '">' + aka + "</a>")
  //-->
</script>
<noscript>
Suchtprophylaxe
</noscript>
in der Berliner Schule</div>
