<?
/*
        Copyright (C) 2000-2003 Liquid Bytes (R) Technologies, Germany. All rights reserved.
        http://www.liquidbytes.net/

        This file is part of the Liquid Bytes (R) Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 21.08.2003
*/

?>
<center>
<br /><br />
<span style="font-size:11px">
Copyright &copy; 2000-2003 <a href="http://www.liquidbytes.net/">Liquid Bytes&reg; Technologies, Germany</a>. All rights reserved.
</span>
</center>
<br />
