<?php
/*
        Copyright (C) 2000-2003 Liquid Bytes (R) Technologies, Germany. All rights reserved.
        http://www.liquidbytes.net/

        This file is part of the Liquid Bytes (R) Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 21.08.2003
*/


?>
<link rel="stylesheet" type="text/css" href="admin.css" />

</head>

<body bgcolor="#ffffff" topmargin="0" rightmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
<table width="100%" height="90" cellpadding="0" cellspacing="0" border="0">
<tr>
<td width="100%" bgcolor="#F9FBFF">
<img src="img/awf.png" border="0" hspace="0" vspace="0" />
&nbsp;</td>
<td width="366" height="90" bgcolor="#F9FBFF" align="right" valign="top" 
background=""><a href="http://www.liquidbytes.net/awf/"><img src="img/logo.png" 
border="0" width="366" height="90" hspace="0" vspace="0"></a></td>
</tr>

<tr bgcolor="#008ace">
<td colspan="2" align="left"><table cellpadding="1" cellspacing="0" border="0">
<tr>
<td>&nbsp;</td>
<?php include('make_nav.inc'); ?>
</tr>
</table></td>
</tr>
</table>
<br />
<br />
<center>
